### ISSUE TITLE
use "not dangerous" looking parameter identifier + consistence

### ISSUE THREAD

**Issue by hpvd** [PiwikPRO/plugin-AdvancedCampaignReporting#22]
This add-on is really great!

But lots of people do not like marketing and tracking at all.

So if it happen that they see a full link (instead of it's link-text) which contains "dangerous" words like "campaign" and which is in addition very long they won't use it :-(

=> To prevent this, we should have more friendly looking short words as parameter identifiers or simply their abbreviation (short version)

e.g.
pk_campaign => pk_cn
pk_keyword => pk_kd
pk_medium => pk_md
...

maybe some of this is already possible
via. https://github.com/PiwikPRO/plugin-AdvancedCampaignReporting/issues/8

or it's the same which is meant here in "Ideas for improvement" on  https://plugins.piwik.org/AdvancedCampaignReporting

if so: hmmm -what's the status? I couldn't find a documentation. Please add a tiny table in documentation what is possible!

In addition: what should be used as best practices?
e.g.
here https://piwik.org/docs/tracking-campaigns/  we are talking about the "pk_campaign" and "pk_keyword" (long "dangerous" versions)
but the urls generated with great
https://piwik.org/docs/tracking-campaigns-url-builder/
contains "pk_campaign" and "pk_kwd" (long and short mixed)

=> what would be the 5
- best looking (for users) and
- best working (compatibility to google)
abbreviations?

(hmm sorry I have messed up with piwik standard tracking and the additional one from this add-on -> the written would be good for both places and should be consistent...)

**Comment by mattab** [comment]
Hi @hpvd
you can see the alias of the parameter in the global config: https://github.com/piwik/piwik/blob/2.13.1/config/global.ini.php#L621-631

Feel free to use whatever one you prefer. if you have suggestion to improve the campaign URL builder feel free to create an issue at: https://github.com/piwik/piwik

Thanks!

**Comment by hpvd** [comment]
Hi @mattlab,

thanks for pointing me to this list of alternatives for piwik's
pk_campaign
pk_keyword

is there something similar for the 5 parameters from advancedcampaignreporting plugin?
