### ISSUE TITLE
segment-editor: campaign category not visible

### ISSUE THREAD

**Issue by hpvd** [PiwikPRO/plugin-AdvancedCampaignReporting#23]
after testing with good result a simple campaign tracking
.... using html?pk_campaign=kont&pk_kwd=blog

(piwik 2.14.0-b3, advancedcampaignreporting  1.0.8 )

I tried to use the segment editor.

From feature description there should be:
"Segment editor: a new "Campaigns" category lists the five new segment for each campaign dimension"

but I couldn't find any entry in segment editor
is it working in other installations? Is there something to set up? should it work out of the box?
Is there somewhere a screenshot how it should look?

![2015-06-16_20h01_15](https://cloud.githubusercontent.com/assets/5681880/8190433/b5d210e6-1462-11e5-9b04-eb2830e4f742.png)

![2015-06-16_20h13_07](https://cloud.githubusercontent.com/assets/5681880/8190644/28aa664e-1464-11e5-87c0-9f1704f2f1c0.png)

**Comment by mattab** [comment]
Hi @hpvd 

In the Segment editor you should see the `Campaigns` category letting you create segment for any of the campaign dimension. See this screenshot:

![campaign segment editor](https://cloud.githubusercontent.com/assets/466765/8223715/c11c1c9e-15cf-11e5-9272-d48c4aa835dd.png)


It looks different for you, can you confirm you don't see this?

**Comment by hpvd** [comment]
Hi @mattlab,

thanks for the screenshot! This is excatly what I was looking for. But this new category is not visible in my installation (see also my screenshot above, piwik 2.14.0-b3, advancedcampaignreporting 1.0.8 )

**Comment by hpvd** [comment]
hmm after deactivating and reactivating the plugin it's now there.
please see attachment.

Don't know why. 
**=> Ticket can be closed!**

![2015-06-18_07h36_33](https://cloud.githubusercontent.com/assets/5681880/8224812/11dc1c30-158d-11e5-8a2b-24f071abc223.png)

**Comment by mattab** [comment]
@hpvd that's quite strange indeed! But i'm closing :-)
