### ISSUE TITLE
campaign reporting: 6 headlines for 5 parameters

### ISSUE THREAD

**Issue by hpvd** [PiwikPRO/plugin-AdvancedCampaignReporting#27]
campaign reporting: 6 headlines for 5 parameters please see attachment
hmm shouldn't it be only 5 headlines (one for each parameter)?

![2015-06-18_13h32_44](https://cloud.githubusercontent.com/assets/5681880/8230318/5d78b298-15bf-11e5-977a-3f62ec3b5288.png)

on the screenshots within the plug-in description it looks the same (6to5)
https://plugins.piwik.org/AdvancedCampaignReporting

**Comment by svenjuhnke** [comment]
"Campaign Source - Medium" combines "Campaign Sources" with "Campaign Mediums"
